apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-koi-cbs
spec:
  selector:
    matchLabels:
      app: mysql-koi-cbs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-koi-cbs
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-koi-cbs
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      ports:
      - containerPort: 3306
        name: mysql-koi-cbs
      volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
    volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pvc-koi-cbs
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-koi-cbs-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-koi-cbs