network:
  ethernets:
    eno2:
      dhcp4: no
  bridges:
    br-ex:
      dhcp4: no
      addresses: [192.168.1.7/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      interfaces:
            - eno2
  version: 2
  renderer: networkd